format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32CM_JH_Curiosity_Pro, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '500', y: '20', id: BSP_PIC32CM_JH_Curiosity_Pro}
